apiVersion: v1
kind: ServiceAccount
metadata:
  name:  pcs-cluster
  namespace: example
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pcs-cluster
  namespace: example
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pcs-cluster
  namespace: example
subjects:
- kind: ServiceAccount
  name:  pcs-cluster
  namespace: example
roleRef:
  kind: ClusterRole
  name: pcs-cluster
  apiGroup: rbac.authorization.k8s.io
