apiVersion: v1
kind: ServiceAccount
metadata:
  name:  cluster-admin
  namespace: example

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin
  namespace: example
rules:
- apiGroups:
    - '*'
  resources:
    - '*'
  verbs:
    - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name:  cluster-admin
    namespace: example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
